######### admin Token 발급 #########################################################################################################################
##### Obtain access token for a user
#POST /realms/master/protocol/openid-connect/token HTTP/1.1
#Host: accounts.hqloud.blocksmith.xyz
#Content-Type: application/x-www-form-urlencoded
#Content-Length: 67
#
#client_id=admin-cli&username=platpome-client-admin&password=PxQXumrHTgYw8BA&grant_type=password
#
#> {% client.global.set("access_token", response.body.access_token); %}

### admin Token 발급
POST /realms/master/protocol/openid-connect/token HTTP/1.1
Host: accounts.hqloud.blocksmith.xyz
Content-Type: application/x-www-form-urlencoded
Content-Length: 106

client_id=platpome-client-admin&client_secret=9spoKyl53wfThnbbOmP8zts21AgNIRQO&grant_type=client_credentials

> {% client.global.set("access_token", response.body.access_token); %}

#########################################################################################################################

#### 클라이언트 생성 (admin Token)
POST https://accounts.hqloud.blocksmith.xyz/admin/realms/platpome/clients
accept: application/json, text/plain, */*
authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "protocol": "openid-connect",
  "clientId": "test3",
  "name": "",
  "description": "",
  "publicClient": false,
  "authorizationServicesEnabled": false,
  "serviceAccountsEnabled": true,
  "implicitFlowEnabled": true,
  "directAccessGrantsEnabled": true,
  "standardFlowEnabled": true,
  "frontchannelLogout": true,
  "attributes": {
    "saml_idp_initiated_sso_url_name": "",
    "oauth2.device.authorization.grant.enabled": false,
    "oidc.ciba.grant.enabled": false
  },
  "alwaysDisplayInConsole": false,
  "rootUrl": "",
  "baseUrl": "",
  "webOrigins": [
    "*"
  ]
}

### 클라이언트정보, 클라이언트시크릿 조회 - 사용자가 생성한 client_id
GET /admin/realms/platpome/clients?clientId=APP_1 HTTP/1.1
Host: accounts.hqloud.blocksmith.xyz
authorization: Bearer {{access_token}}

> {% client.global.set("client_uid", response.body[0].id); %}

### Client secret generate ( 기존 키 초기화되고 재발급됩니다. 주의! )
POST /admin/realms/platpome/clients/354f845f-f169-4a2f-9e99-b18f3f81f51e/client-secret HTTP/1.1
Content-Type: application/json
Host: accounts.hqloud.blocksmith.xyz
authorization: Bearer {{access_token}}
###
