@startuml
'https://plantuml.com/sequence-diagram


actor 통합인증관리자
actor 게임개발자

autonumber
group adminToken 발급
콘솔 -> 통합인증: token request (client_credentials)
콘솔 <- 통합인증: token response
end
note across: Token 만료에 대한 정책 및 만료시 대응 방법이 필요\n 일단 만료 안함. 권한에서 삭제 권한을 뺴려고했는데, 통합인증에서 하나의 권한으로 되어있음.

group 클라이언트 생성 (adminToken)
게임개발자 -> 콘솔: 앱추가
콘솔 -> 콘솔: adminToken 검증
콘솔 -> 통합인증: 앱정보로 클라이언트 생성
콘솔 <- 통합인증: 클라이언트정보, 클라이언트시크릿
group 클라이언트 시크릿 재 발급
게임개발자 -> 콘솔: 시크릿 재발급
콘솔 -> 통합인증: 클라이언트 시크릿 재 발급 요청
콘솔 <- 통합인증: 클라이언트 시크릿 재 발급 응답( with new secret )
end
end

group 앱서버에서 client 토큰 발급 (with client secret)
게임개발자 -> 앱서버: client secret 저장
앱서버 -> 통합인증: token발급 요청( client id / client secret)
앱서버 <- 통합인증: token발급 응답
end

group 앱서버에서 platpome 리소스 서버 호출
앱서버 -> Resource서버: private resource request ( client token )
group 토큰 검증
Resource서버 -> Resource서버: 토큰 verify 절차
Resource서버 -> 통합인증: jwks PublicKey 조회
통합인증 -> Resource서버: jwks PublicKey 응답
note across: jwk publickey 캐시
Resource서버 -> Resource서버: 토큰 verify 끝
end
앱서버 <- Resource서버: private resource response ( client token )
end

@enduml
